-- =============================================================================
-- Example Flyway Migration: Initial Schema with Row-Level Security
-- =============================================================================
--
-- This migration demonstrates the required RLS (Row-Level Security) pattern
-- for all Servista tables that contain organization-scoped data.
--
-- Key points:
--   - Every table with organization_id MUST follow this pattern
--   - app.current_organization_id is set by RlsSessionManager.withOrganization()
--     from servista-commons on every database request
--   - Without FORCE ROW LEVEL SECURITY, the table owner (which is often the
--     application's DB user) bypasses the policy entirely -- this is a critical
--     security requirement
--
-- Flyway conventions:
--   - Migration files go in src/main/resources/db/migration/ in each service
--   - Naming: V{number}__{description}.sql (note: double underscore)
--   - Migrations are applied automatically on startup via Flyway integration
--
-- CUSTOMIZE for your service:
--   - Rename "example_entity" to your actual table name
--   - Add your domain-specific columns
--   - Update the RLS policy name to match your table
--   - Add indexes for your query patterns
--
-- =============================================================================

-- Create the example table
-- id: Snowflake ID generated by servista-commons IdGenerator
-- organization_id: tenant scope for RLS isolation
CREATE TABLE example_entity (
    id                BIGINT       PRIMARY KEY,
    organization_id   BIGINT       NOT NULL,
    name              TEXT         NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Index on organization_id for efficient tenant-scoped queries
CREATE INDEX idx_example_entity_organization ON example_entity (organization_id);

-- =============================================================================
-- Row-Level Security (RLS) -- MANDATORY for all organization-scoped tables
-- =============================================================================

-- Step 1: Enable RLS on the table
ALTER TABLE example_entity ENABLE ROW LEVEL SECURITY;

-- Step 2: Create tenant isolation policy
-- This policy restricts all queries to rows matching the current organization.
-- The session variable app.current_organization_id is set by
-- RlsSessionManager.withOrganization() from servista-commons before each
-- database operation.
CREATE POLICY tenant_isolation ON example_entity
    USING (organization_id = current_setting('app.current_organization_id')::BIGINT);

-- Step 3: FORCE RLS for the table owner
-- CRITICAL: Without this, the table owner (typically the application's DB user)
-- bypasses RLS entirely. This is PostgreSQL's default behavior and is a
-- significant security gap if not addressed.
ALTER TABLE example_entity FORCE ROW LEVEL SECURITY;
